development:
  adapter: postgresql
  encoding: unicode
  database: mariokart
  username: Thomas
  password:
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>